language: node_js
node_js: 
  - "iojs"
  - "7"
build: npm run build
deploy:
  provider: s3
  access_key_id: AKIAICQFURJ2WWOSZE6A
  secret_access_key:
    secure: F/LBSSlU+X7ioJsR8Cw/MENG0iS1f77UIA4KFTUfrczd95YeBgOpY3T83woYy/Nr+nVwlyM/qPKukcUFIdfGjgQqrAN2xYZ+QNcVTvnKi6I5n1Gw1zDCi4vynqls9L8P8WPnrrpT0TTQDdzQpvL2a9KOVXvuT9QDf7x++RzFMjmIa/r3HaJgld2DzHq6RrEZsa3/9rMfhfCkd52rDPFkRajBzz3FknBdG/uB3ayo15GIlaJ7r9s267CzLo/Eyu9rAgGx43QWmLP/VTqeIk7L2ys/fSi+kc6NtihCpWitXYldGPflFIBalNGYIBNU4/x3gLoaExAnVMUFthKHbp2eo1Ll5WsCdU7h0h4nR6Ty+6q8lgGdVd/B5gIxQMReGJjbzagvnqeVcJNBn9Tt5Y0aYofT6FkfECp1680OMmwwxAgGIswMfnbZf4YPwTBPBupHQDGB9GK/rJTpsLF6DxvT7LopjXxwtGwN1/BRMjqB7WRS8kqo8LwjfRhXDB5opGT/fnzY/WkLDLfYxlA+zdTqFN7Ggr9VuUXWxtvpp5ewXdLQm6J0UjZuJHfM+QMfVaKZCZwi7wfZP8r8j7sNF9SjhoG5dPJz6bfX2V+4SgLothbdPGj3D5uK4VrO3uyUkT0dnUQ4ZTbiCcLh6zv8PLfiUNHQWuvj2/QNB/1YHMmMau8=
  bucket: play.tcreeds.io
  local_dir: build
